image:
  repository: ghcr.io/okapi-core/ops
  tag: latest
  pullPolicy: IfNotPresent

job:
  backoffLimit: 3
  activeDeadlineSeconds: 900
  ttlSecondsAfterFinished: 86400

clickhouse:
  host: clickhouse
  port: 8123
  secure: false
  username: default
  password: ""
  existingSecret: ""
  usernameKey: username
  passwordKey: password

postgres:
  url: jdbc:postgresql://postgres:5432/okapi_oscar?currentSchema=okapi_web
  username: ""
  password: ""
  existingSecret: ""
  usernameKey: migration-username
  passwordKey: migration-password

podAnnotations: {}
podLabels: {}
nodeSelector: {}
tolerations: []
affinity: {}
resources: {}
