cookies.secure=true
server.port=8080
okapi.ch.wal.consumeIntervalMs=200
okapi.ch.wal.batchSize=64
okapi.nodes.nodeIdFile=./node-id-test
okapi.cluster.clusterId=test-cluster
okapi.cluster.streamRouterCacheMillis=1000
okapi.cluster.namespace=okapi-test-server
okapi.aws.region=eu-west-2
okapi.aws.endpoint=${OKAPI_TEST_AWS_ENDPOINT:https://dynamodb.eu-west-2.amazonaws.com}
okapi.kafka.executors.metricsPoolSize=1
okapi.kafka.executors.metricsDelayJitterMs=100
okapi.kafka.executors.metricsDelayInitialMs=100
okapi.kafka.executors.logsPoolSize=1
okapi.kafka.executors.logsDelayJitterMs=100
okapi.kafka.executors.logsDelayInitialMs=100
okapi.kafka.executors.tracesPoolSize=1
okapi.kafka.executors.tracesDelayJitterMs=100
okapi.kafka.executors.tracesDelayInitialMs=100
okapi.kafka.topics.logsTopic=logs-topic
okapi.kafka.topics.metricsTopic=metrics-topic
okapi.kafka.topics.tracesTopic=traces-topic
okapi.kafka.consumer.logs.maxPollRecords=10
okapi.kafka.consumer.logs.maxPollIntervalMs=300000
okapi.kafka.consumer.logs.bootstrapServers=${OKAPI_TEST_KAFKA_BOOTSTRAP_SERVERS:127.0.0.1:9092}
okapi.kafka.consumer.metrics.maxPollRecords=10
okapi.kafka.consumer.metrics.maxPollIntervalMs=300000
okapi.kafka.consumer.metrics.bootstrapServers=${OKAPI_TEST_KAFKA_BOOTSTRAP_SERVERS:127.0.0.1:9092}
okapi.kafka.consumer.traces.maxPollRecords=10
okapi.kafka.consumer.traces.maxPollIntervalMs=300000
okapi.kafka.consumer.traces.bootstrapServers=${OKAPI_TEST_KAFKA_BOOTSTRAP_SERVERS:127.0.0.1:9092}
okapi.logs.expectedInsertions=1000
okapi.logs.maxPageWindowMs=600000
okapi.logs.maxPageBytes=4096
okapi.logs.bloomFpp=0.05
okapi.logs.sealedPageCap=20
okapi.logs.sealedPageTtlMs=10000
okapi.logs.dataDir=data-dir
okapi.logs.idxExpiryDuration=10000
okapi.logs.s3Bucket=s3-logs-bucket
okapi.logs.s3BasePrefix=logs
okapi.logs.s3UploadGraceMs=0
okapi.logs.bufferPoolFlushEvalMillis=100
okapi.metrics.expectedInsertions=1000
okapi.metrics.maxPageWindowMs=600000
okapi.metrics.maxPageBytes=4096
okapi.metrics.bloomFpp=0.05
okapi.metrics.sealedPageCap=20
okapi.metrics.sealedPageTtlMs=10000
okapi.metrics.dataDir=metrics-data-dir
okapi.metrics.idxExpiryDuration=10000
okapi.metrics.s3Bucket=s3-data-bucket
okapi.metrics.s3BasePrefix=metrics
okapi.metrics.s3UploadGraceMs=0
okapi.metrics.bufferPoolFlushEvalMillis=100
okapi.traces.expectedInsertions=1000
okapi.traces.maxPageWindowMs=600000
okapi.traces.maxPageBytes=4096
okapi.traces.bloomFpp=0.05
okapi.traces.sealedPageCap=20
okapi.traces.sealedPageTtlMs=10000
okapi.traces.dataDir=traces-data-dir
okapi.traces.idxExpiryDuration=10000
okapi.traces.s3Bucket=s3-traces-bucket
okapi.traces.s3BasePrefix=traces
okapi.traces.s3UploadGraceMs=0
okapi.traces.bufferPoolFlushEvalMillis=100
okapi.query.logsQueryProcPoolSize=1
okapi.query.metricsQueryProcPoolSize=1
okapi.query.tracesQueryProcPoolSize=1
okapi.query.logsFanoutPoolSize=1
okapi.query.metricsFanoutPoolSize=1
okapi.query.tracesFanoutPoolSize=1
okapi.query.logsFanoutTimeoutMs=100
okapi.query.metricsFanoutTimeoutMs=100
okapi.query.tracesFanoutTimeoutMs=100
okapi.s3.upload.uploadDelayMs=100
okapi.zk.connectString=${OKAPI_TEST_ZOOKEEPER_CONNECT_STRING:127.0.0.1:2181}
okapi.zk.backoffMillis=1000
okapi.zk.retries=2
