server.port=9009
okapi.telemetry.otlp.metrics.endpoint=${OKAPI_OTEL_METRICS_ENDPOINT:${OTEL_EXPORTER_OTLP_METRICS_ENDPOINT:}}
okapi.telemetry.otlp.metrics.step=${OKAPI_OTEL_METRICS_STEP:15s}
okapi.clickhouse.migrateOnStartup=false
okapi.clickhouse.host=${OKAPI_CLICKHOUSE_HOST:127.0.0.1}
okapi.clickhouse.port=${OKAPI_CLICKHOUSE_PORT:8123}
okapi.clickhouse.username=default
okapi.clickhouse.password=okapi_testing_password
okapi.clickhouse.chMetricsWalCfg.segmentSize=1024
okapi.clickhouse.chLogsCfg.segmentSize=1024
okapi.clickhouse.chTracesWalCfg.segmentSize=1024
okapi.clickhouse.chMetricsWal=${user.home}/ch-wal/metrics
okapi.clickhouse.chLogsWal=${user.home}/ch-wal/logs
okapi.clickhouse.chTracesWal=${user.home}/ch-wal/traces
okapi.metrics.consumptionType=wal
okapi.metrics.otel.converter.excludeTags=success,type
okapi.metrics.otel.converter.excludeTagPrefixes=telemetry.sdk
okapi.traces.consumptionType=wal
