orgId: testOrg
spring:
  mvc:
    converters:
      preferred-json-mapper: gson

clusterEndpoint: ${OKAPI_CLUSTER_ENDPOINT:http://127.0.0.1:9009}
oscarEndpoint: ${OKAPI_OSCAR_ENDPOINT:http://127.0.0.1:9002}
cookies:
  secure: false

server:
  port: 9001

query:
  threads: 10
  nParallel: 5
  timeout: 3000

okapi:
  s3:
    bucket: okapi-data-bucket
    resultsPrefix: query-results

  aws:
    creds: env
    region: us-west-2
    endpoint: ${OKAPI_AWS_ENDPOINT:http://127.0.0.1:4566}

  federation:
    agent:
      http:
        endpoint: ${OKAPI_OSCAR_ENDPOINT:http://127.0.0.1:9002}

    polling-task:
      initial-delay-ms: 1000
      max-attempts: 5
