spring.mvc.converters.preferred-json-mapper=gson
clusterEndpoint=${OKAPI_CLUSTER_ENDPOINT:http://127.0.0.1:9009}
oscarEndpoint=${OKAPI_OSCAR_ENDPOINT:http://127.0.0.1:9002}
cookies.secure=false
server.port=9001
query.threads=10
query.nParallel=5
query.timeout=3000
okapi.org.orgId=${OKAPI_ORG_ID:default}
okapi.org.orgName=${OKAPI_ORG_NAME:default}