apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clickhouse.fullname" . }}-cluster
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
data:
  okapi-cluster.xml: |
    <clickhouse>
      <listen_host>0.0.0.0</listen_host>
      <remote_servers>
        <{{ .Values.cluster.name }}>
          {{- range $ordinal := until (int .Values.cluster.shards) }}
          <shard>
            <internal_replication>true</internal_replication>
            <replica>
              <host>{{ include "clickhouse.fullname" $ }}-{{ $ordinal }}.{{ include "clickhouse.fullname" $ }}-headless</host>
              <port>{{ $.Values.service.nativePort }}</port>
              <user>default</user>
              <password>{{ $.Values.auth.password }}</password>
            </replica>
          </shard>
          {{- end }}
        </{{ .Values.cluster.name }}>
      </remote_servers>
      {{- if .Values.zookeeper.enabled }}
      <zookeeper>
        <node>
          <host>{{ include "clickhouse.fullname" . }}-zookeeper</host>
          <port>2181</port>
        </node>
      </zookeeper>
      {{- end }}
      <distributed_ddl>
        <path>/clickhouse/task_queue/ddl</path>
      </distributed_ddl>
    </clickhouse>
