apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clickhouse.fullname" . }}-macros
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
data:
  macros.xml: |
    <clickhouse>
      <macros>
        <cluster>__CLUSTER_NAME__</cluster>
        <shard>__SHARD__</shard>
        <replica>__REPLICA__</replica>
      </macros>
    </clickhouse>
