CREATE TABLE IF NOT EXISTS okapi_logs.logs_table_v1
(
    ts_ns Int64,
    log_stream LowCardinality(String),
    service_name LowCardinality(String),
    log_level Int32,
    severity_text LowCardinality(String),
    trace_id String CODEC(ZSTD),
    span_id String CODEC(ZSTD),
    body String CODEC(ZSTD),
    resource_attribs_str_0 Map(String, String),
    resource_attribs_str_1 Map(String, String),
    resource_attribs_str_2 Map(String, String),
    resource_attribs_str_3 Map(String, String),
    resource_attribs_str_4 Map(String, String),
    resource_attribs_str_5 Map(String, String),
    resource_attribs_str_6 Map(String, String),
    resource_attribs_str_7 Map(String, String),
    resource_attribs_str_8 Map(String, String),
    resource_attribs_str_9 Map(String, String),
    resource_attribs_number_0 Map(String, Float64),
    resource_attribs_number_1 Map(String, Float64),
    resource_attribs_number_2 Map(String, Float64),
    resource_attribs_number_3 Map(String, Float64),
    resource_attribs_number_4 Map(String, Float64),
    resource_attribs_number_5 Map(String, Float64),
    resource_attribs_number_6 Map(String, Float64),
    resource_attribs_number_7 Map(String, Float64),
    resource_attribs_number_8 Map(String, Float64),
    resource_attribs_number_9 Map(String, Float64),
    attribs_str_0 Map(String, String),
    attribs_str_1 Map(String, String),
    attribs_str_2 Map(String, String),
    attribs_str_3 Map(String, String),
    attribs_str_4 Map(String, String),
    attribs_str_5 Map(String, String),
    attribs_str_6 Map(String, String),
    attribs_str_7 Map(String, String),
    attribs_str_8 Map(String, String),
    attribs_str_9 Map(String, String),
    attribs_number_0 Map(String, Float64),
    attribs_number_1 Map(String, Float64),
    attribs_number_2 Map(String, Float64),
    attribs_number_3 Map(String, Float64),
    attribs_number_4 Map(String, Float64),
    attribs_number_5 Map(String, Float64),
    attribs_number_6 Map(String, Float64),
    attribs_number_7 Map(String, Float64),
    attribs_number_8 Map(String, Float64),
    attribs_number_9 Map(String, Float64),
    INDEX body_text_idx(body) TYPE text(tokenizer = 'splitByNonAlpha') GRANULARITY 1
)
ENGINE = MergeTree
PARTITION BY toStartOfHour(toDateTime(ts_ns / 1000000000))
ORDER BY (service_name, trace_id, span_id, ts_ns, log_stream, log_level);
